---
- name: Configure webserver with nginx
  hosts: webservers
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/conf.d/default.conf
    server_name: localhost
  tasks:
    - name: setup yum repo of nginx
      ansible.builtin.template:
        src: files/nginx.repo
        dest: /etc/yum.repos.d/nginx.repo

    - name: install nginx
      yum:
        name: nginx
        update_cache: yes
        state: latest

    - name: create directories for ssl certificates
      ansible.builtin.file:
        path: /etc/nginx/ssl
        state: directory

    - name: copy TLS key
      ansible.builtin.copy:
        src: files/nginx.key
        dest: "{{ key_file }}"
        owner: root
        mode: '0600'
      notify: restart nginx

    - name: copy TLS certificate
      ansible.builtin.copy:
        src: files/nginx.cert
        dest: "{{ cert_file }}"
      notify: restart nginx

    - name: copy nginx config file
      ansible.builtin.template:
        src: templates/nginx.conf.j2
        dest: "{{ conf_file }}"
      notify: restart nginx

    - name: copy index.html
      ansible.builtin.template:
        src: templates/index.html.j2
        dest: /usr/share/nginx/html/index.html
        mode: '0644'

  handlers:
    - name: restart nginx
      ansible.builtin.service:
        name: nginx
        state: restarted

