---
mezzanine_user: "{{ ansible_ssh_user }}"
mezzanine_venv_home: "{{ ansible_env.HOME }}"
mezzanine_venv_path: "{{ mezzanine_venv_home }}/{{ mezzanine_project_name }}"
mezzanine_repo_url: git@github.com:lorin/mezzanine-example.git
mezzanine_project_dirname: project
mezzanine_project_path: "{{ mezzanine_venv_path }}/{{ mezzanine_project_dirname }}"
mezzanine_reqs_path: requirements.txt
mezzanine_conf_path: /etc/nginx/conf
mezzanine_python: "{{ mezzanine_venv_path }}/bin/python"
mezzanine_manage: "{{ mezzanine_python }} {{ mezzanine_project_path }}/manage.py"
mezzanine_gunicorn_port: 8000
