---
- name: Configure webserver with nginx
  hosts: development
  become: True
  vars:
    key_file: /etc/nginx/ssl/nginx.key
    cert_file: /etc/nginx/ssl/nginx.crt
    conf_file: /etc/nginx/conf.d/default.conf
    local_vars_dirs: /etc/ansible/facts.d/
    server_name: localhost
  tasks:
    - name: print vars
      ansible.builtin.debug:
        msg: "key_file={{ key_file }}, cert_file={{ cert_file }}, conf_file={{ conf_file }}, server_name={{ server_name }}"

    - name: capture output of id command
      command: id -un
      register: login
    - debug: msg="Logged in as user {{ login.stdout }}"

    - debug: var=ansible_distribution

    - name: create ansible local directory.
      ansible.builtin.file:
        path: "{{ local_vars_dirs }}/"
        state: directory
        mode: '0755'

    # - name: copy ansible local vars.
    #   ansible.builtin.copy:
    #     src: files/variable.fact
    #     dest: "{{ local_vars_dirs }}/variable.fact"
    #     mode: '0755'

    - set_fact: title="The first Ansible."
    # - debug: msg="{{ hostvars['testserver'].ansible_all_ipv4_addresses[0] }}"
    # - debug: var=hostvars[inventory_hostname]
    - debug: var=groups[webservers]

